NOSWebApp/Controllers/ClubController.cs
using NOSWebApp.Helpers;
using NOSWebApp.Models;
using NOSWebApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace NOSWebApp.Controllers
{
    [Authorize]
    [HandleError]
    public class ClubController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Club
        [Authorize]
        public ActionResult Index(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "No Club Given");
            }

            Club club = null;
            try
            {
                 club = db.Clubs.FirstOrDefault(c => c.ClubId == id);

            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, ex.Message);
            }

            if(club == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound, "Club not Found");
            }

            ClubStatsView clubStatsView = new ClubStatsView
            {
                Club = club,
                SeasonsPlayed = club.SeasonPlayed.ToList(),
            };

            return View(clubStatsView);
        }

        [Authorize]
        public ActionResult AllStats(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "No Club Given");
            }

            Club club = null;
            try
            {
                club = db.Clubs.FirstOrDefault(c => c.ClubId == id);
            }
            catch(Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, ex.Message);
            }

            if (club == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound, "Club not Found");
            }

            List<GameMatch> clubGameMatches = null;

            try
            {
                clubGameMatches = db.GameMatches.Where(gm => gm.HomeClub.ClubId == club.ClubId || gm.AwayClub.ClubId == club.ClubId).ToList();
            }
            catch(Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, ex.Message);
            }

            if(clubGameMatches == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            ClubStatsView clubStatsView = null;

            try
            {
                clubStatsView = StatusHelper.MakeClubStats(club, clubGameMatches);
            }
            catch(Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, ex.Message);
            }

            if(clubStatsView == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            return View(clubStatsView);
        }

        [Authorize]
        public ActionResult AllSeasonClubStats(int? id, int? seasonId)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "No Club Given");
            }

            Club club = null;
            try
            {
                club = db.Clubs.FirstOrDefault(c => c.ClubId == id);
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, ex.Message);
            }

            if (club == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound, "Club not Found");
            }

            if (seasonId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "No Season Given");
            }

            List<GameMatch> clubGameMatches = null;

            try
            {
                clubGameMatches = db.GameMatches.Where(gm => (gm.HomeClub.ClubId == club.ClubId || gm.AwayClub.ClubId == club.ClubId) && gm.Fixture.SeasonId == seasonId).ToList();
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            if(clubGameMatches == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            ClubStatsView clubStatsView = null;

            try
            {
                clubStatsView = StatusHelper.MakeClubSeasonStats(club, clubGameMatches);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            if(clubStatsView == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            return View(clubStatsView);
        }

        [Authorize]
        public ActionResult ClubFans(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Club club = null;
            try
            {
             club =   db.Clubs.FirstOrDefault(c => c.ClubId == id);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            if(club == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            return View(club);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NOSWebApp/Controllers/DashboardController.cs
using Microsoft.AspNet.Identity;
using NOSWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace NOSWebApp.Controllers
{
    [Authorize]
    [HandleError]
    public class DashboardController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Dashboard
        [Authorize]
        public ActionResult Home(string id)
        {
            
            var users = db.Users;

            ApplicationUser user = null;

            if (id == null)
            {
                try
                {
                    var thisUserId = User.Identity.GetUserId().ToUpper();

                    user = users.FirstOrDefault(u => u.Id.ToUpper() == thisUserId);

                    user.FavouriteClub = db.Clubs.FirstOrDefault(c => c.ClubId == user.ClubId);

                    return View(user);
                }
                catch
                {
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
                }
            }

            try
            {
                user = users.FirstOrDefault(u => u.Id.ToUpper() == id.ToUpper());

                user.FavouriteClub = db.Clubs.FirstOrDefault(c => c.ClubId == user.ClubId);


                return View(user);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        [Authorize]
        public ActionResult Bank()
        {

            return View();
        }

        [Authorize]
        public ActionResult AddMoney(string userId, double moneyToAdd)
        {
            if(userId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            if(moneyToAdd == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                var user = db.Users.FirstOrDefault(u => u.Id.ToUpper() == userId.ToUpper());

                user.BankAccount += moneyToAdd;

                db.Entry(user).State = System.Data.Entity.EntityState.Modified;

                db.SaveChanges();

                return RedirectToAction("Bank");
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        [Authorize]
        public ActionResult About()
        {
            return View();
        }

        [Authorize]
        public ActionResult Contact()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NOSWebApp/Views/Dashboard/About.cshtml
@{
    ViewBag.Title = "About";
}

<h2>About</h2>

<br />

<h3>Disclaimer</h3>
<p>This is not a real betting website, but instead a school project</p>

<br />

<h3>Made By:</h3>
<p>Rúben Mateus - CET37 - TPSI</p>
<p>05/2019</p>

NOSWebApp/Views/Dashboard/Bank.cshtml
@using NOSWebApp.Extensions
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Bank";
}

<h2>Bank</h2>

<div class="row mt-3">

    <div class="col-sm-4 text-center my-2">

        <a href="@Url.Action("AddMoney","Dashboard",new {userId = User.Identity.GetUserId() , moneyToAdd = 100})" class="row h-100 align-items-center border py-3 mx-1" id="LeagueBox">

            <div class="col-12 text-center">
                <h3>Little Spender</h3>
            </div>


            <div class="col-12 text-center pb-2 mt-3">

                <img src="~/Media/Shared/Navbar/BetTilSmallLogo.png" class="img-fluid" style="max-height:175px" />
            </div>

            <div class="col-12 align-self-end text-center mt-3">
                <span>ADD 100 COINS!</span>
            </div>

        </a>





    </div>

    <div class="col-sm-4 text-center my-2">

        <a href="@Url.Action("AddMoney","Dashboard",new {userId = User.Identity.GetUserId() , moneyToAdd = 250})" class="row h-100 align-items-center border py-3 mx-1" id="LeagueBox">

            <div class="col-12 text-center">
                <h3>You got money</h3>
            </div>


            <div class="col-12 text-center pb-2 mt-3">

                <img src="~/Media/Shared/Navbar/BetTilSmallLogo.png" class="img-fluid" style="max-height:175px" />
            </div>

            <div class="col-12 align-self-end text-center mt-3">
                <span>ADD 250 COINS!</span>
            </div>

        </a>





    </div>
    <div class="col-sm-4 text-center my-2">

        <a href="@Url.Action("AddMoney","Dashboard",new {userId = User.Identity.GetUserId() , moneyToAdd = 500})" class="row h-100 align-items-center border py-3 mx-1" id="LeagueBox">

            <div class="col-12 text-center">
                <h3>Kaching!</h3>
            </div>



            <div class="col-12 text-center pb-2 mt-3">

                <img src="~/Media/Shared/Navbar/BetTilSmallLogo.png" class="img-fluid" style="max-height:175px" />
            </div>

            <div class="col-12 align-self-end text-center mt-3">
                <span>ADD 500 COINS!</span>
            </div>

        </a>





    </div>

</div>

NOSWebApp/Views/Dashboard/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<h2>Contact</h2>

<h3 class="mt-3">Found a Problem?</h3>

<p>Do please send an Email to <a href="mailto:ruben.moleiro.mateus@formandos.cinel.pt">ruben.moleiro.mateus@formandos.cinel.pt</a> </p>

NOSWebApp/Views/Dashboard/Home.cshtml
@using NOSWebApp.Extensions
@using NOSWebApp.Helpers

@model NOSWebApp.Models.ApplicationUser

@{
    ViewBag.Title = Model.UserName;
}

<div class="row mt-3">

    <div class="col-md-6">

        <div class="row text-center">

            <div class="col-12">
                <h5>User</h5>
            </div>

            <div class="col-12">
                <img src="@Url.Content(Model.ProfilePic)" height="150" />
            </div>

            <div class="col-12">
                <h2>@Model.UserName</h2>
            </div>

        </div>


    </div>

    <div class="col-md-6">
        @if (Model.FavouriteClub != null)
        {
        <div class="row text-right">

            <div class="col-12">

                <div class="row text-center">

                    <div class="col-12">
                        <h5>Favourite Club</h5>
                    </div>

                    
                        <div class="col-12">
                            <img src="@Url.Content(Model.FavouriteClub.LogoImage)" height="150" />
                        </div>

                        <div class="col-12">
                            <a href="@Url.Action("Index", "Club", new { id = Model.FavouriteClub.ClubId })">
                                <h2>@Model.FavouriteClub.Name.ToUpper()</h2>
                            </a>
                        </div>
                   
                </div>
                
            </div>

        </div>
        }
        else if(User.Identity.Name.ToUpper() == Model.UserName.ToUpper())
        {
            <div class="row text-right ">

                <div class="col-12">
                    <p>Choose Your Favourite Club To its latestes information!</p>
                </div>

                <div class="col-12">
                    <a href="@Url.Action("EditUser","Users",new { userId = Model.Id})">Click Here</a>
                </div>
               
                
            </div>
        }
    </div>

    <div class="col-12">

        <h4 class="mt-3 text-center">Season Player has Participated:</h4>

        <a class="btn btn-primary w-100 mb-2" data-toggle="collapse" href="#swts" role="button" aria-expanded="false" aria-controls="swts">Seasons Waiting To Start</a>
        <div class="collapse" id="swts">

            <div class="table-responsive">

                <table class="table">

                    <thead>
                        <tr class="text-center">
                            <th>Season</th>
                            <th>Season Status</th>
                            <th>Season Pot</th>
                            <th>Season Clubs</th>
                            <th>Season Max Fixtures</th>
                            <th>Season Max GameMatches</th>
                            <th>Season Betters</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var season in Model.SeasonsBetted.Where(s => s.SeasonBetted.SeasonStatus == NOSWebApp.Models.SeasonStatus.WaitingToStart).OrderByDescending(s => s.SeasonId))
                        {
                            <tr class="text-center">
                                <td>@season.SeasonBetted.StartDate.ToShortDateString()</td>
                                <td>@season.SeasonBetted.SeasonStatus</td>
                                <td>@season.SeasonBetted.Betters.Sum(b => b.MoneyBetted) €</td>
                                <td>@season.SeasonBetted.SeasonClubs.Count()</td>
                                <td>@season.SeasonBetted.MaxFixtures</td>
                                <td>@season.SeasonBetted.Fixtures.Sum(f => f.GameMatches.Count())</td>
                                <td>@season.SeasonBetted.Betters.Count() / @season.SeasonBetted.SeasonClubs.Count()</td>
                                <td>@Html.ActionLink("View", "Index", "Season", new { id = season.SeasonId }, null)</td>
                            </tr>
                        }
                    </tbody>

                </table>

            </div>

        </div>

        <a class="btn btn-primary w-100 mb-2" data-toggle="collapse" href="#sip" role="button" aria-expanded="false" aria-controls="sip">Seasons In Pogress</a>
        <div class="collapse" id="sip">

            <div class="table-responsive">

                <table class="table">

                    <thead>
                        <tr class="text-center">
                            <th>Season</th>
                            <th>Season Status</th>
                            <th>Season Pot</th>
                            <th>Season Clubs</th>
                            <th>Season Max Fixtures</th>
                            <th>Season Max GameMatches</th>
                            <th>Season Betters</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var season in Model.SeasonsBetted.Where(s => s.SeasonBetted.SeasonStatus == NOSWebApp.Models.SeasonStatus.InPogress).OrderByDescending(s => s.SeasonId))
                        {
                            <tr class="text-center">
                                <td>@season.SeasonBetted.StartDate.ToShortDateString()</td>
                                <td>@season.SeasonBetted.SeasonStatus</td>
                                <td>@season.SeasonBetted.Betters.Sum(b => b.MoneyBetted) €</td>
                                <td>@season.SeasonBetted.SeasonClubs.Count()</td>
                                <td>@season.SeasonBetted.MaxFixtures</td>
                                <td>@season.SeasonBetted.Fixtures.Sum(f => f.GameMatches.Count())</td>
                                <td>@season.SeasonBetted.Betters.Count() / @season.SeasonBetted.SeasonClubs.Count()</td>
                                <td>@Html.ActionLink("View", "Index", "Season", new { id = season.SeasonId }, null)</td>
                            </tr>
                        }
                    </tbody>

                </table>

            </div>

        </div>

        <a class="btn btn-primary w-100 mb-2" data-toggle="collapse" href="#sf" role="button" aria-expanded="false" aria-controls="sf">Seasons Finished</a>
        <div class="collapse" id="sf">

            <div class="table-responsive">

                <table class="table">

                    <thead>
                        <tr class="text-center">
                            <th>Season</th>
                            <th>Season Status</th>
                            <th>Season Pot</th>
                            <th>Season Clubs</th>
                            <th>Season Max Fixtures</th>
                            <th>Season Max GameMatches</th>
                            <th>Season Betters</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var season in Model.SeasonsBetted.Where(s => s.SeasonBetted.SeasonStatus == NOSWebApp.Models.SeasonStatus.Finished).OrderByDescending(s => s.SeasonId))
                        {
                            <tr class="text-center">
                                <td>@season.SeasonBetted.StartDate.ToShortDateString()</td>
                                <td>@season.SeasonBetted.SeasonStatus</td>
                                <td>@season.SeasonBetted.Betters.Sum(b => b.MoneyBetted) €</td>
                                <td>@season.SeasonBetted.SeasonClubs.Count()</td>
                                <td>@season.SeasonBetted.MaxFixtures</td>
                                <td>@season.SeasonBetted.Fixtures.Sum(f => f.GameMatches.Count())</td>
                                <td>@season.SeasonBetted.Betters.Count() / @season.SeasonBetted.SeasonClubs.Count()</td>
                                <td>@Html.ActionLink("View", "Index", "Season", new { id = season.SeasonId }, null)</td>
                            </tr>
                        }
                    </tbody>

                </table>

            </div>

        </div>

    </div>

</div>