NOSWebApp/Models/League.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace NOSWebApp.Models
{
    public class League
    {
        [Key]
        public int LeagueId { get; set; }
        
        [Required]
        [MinLength(3)]
        public string Name { get; set; }

        public string Description { get; set; }

        public string LogoImage { get; set; } = "~/Media/Shared/noImageAvailable.png";

        public bool IsActive { get; set; } = true;

        #region Navigation

        [NotMapped]
        public virtual HttpPostedFileBase ImageUrl { get; set; }

        public virtual ICollection<Club> Clubs { get; set; } 
        
        public virtual ICollection<Season> Seasons { get; set; }

        #endregion

        
    }
}

NOSWebApp/Controllers/LeagueController.cs
using NOSWebApp.Helpers;
using NOSWebApp.Models;
using NOSWebApp.ViewModels;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace NOSWebApp.Controllers
{
    [Authorize]
    public class LeagueController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: League
        [Authorize]
        public ActionResult Index(int? id, string errorMessage)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            try
            {
                var league = db.Leagues.FirstOrDefault(l => l.LeagueId == id);

                if(league == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var leagueStatsView = StatusHelper.MakeLeagueStats(league);

                ViewBag.ErrorMessage = errorMessage;
                return View(leagueStatsView);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

        }

        [Authorize(Roles = "LeagueAdmin")]
        public ActionResult AddSeason(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var league = db.Leagues.FirstOrDefault(l => l.LeagueId == id);

            if(league == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            if (!league.IsActive)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (league != null && league.IsActive)
            {
                if (league.Clubs.Where(c => c.IsActive).Count() >= 4)
                {
                    try
                    {
                        var newSeason = LeagueHelper.CreateSeason(league);

                        if(newSeason == null)
                        {
                            return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
                        }

                        league.Seasons.Add(newSeason);

                        db.Seasons.Add(newSeason);
                        db.Entry(league).State = EntityState.Modified;

                        db.SaveChanges();

                        return RedirectToAction("Index", new { id = id });
                    }
                    catch
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
                    }
                }

                    return RedirectToAction("Index", new { id = league.LeagueId, errorMessage = "Not enough active clubs to start season!" });

            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [Authorize(Roles = "LeagueAdmin")]
        public ActionResult CancelSeason(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var season = db.Seasons.FirstOrDefault(s => s.SeasonId == id);

            if(season == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            if(season.Betters.Count() != 0)
            {
                return RedirectToAction("Index", new { id = season.LeagueId, errorMessage = "You can't disable a season that has betters!" });
            }

            if (season.SeasonStatus != SeasonStatus.WaitingToStart)
            {
                return RedirectToAction("Index", new { id = season.LeagueId, errorMessage = "You can only disable seasons that are about to start!" });
            }


            if (!season.League.IsActive)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                season.SeasonStatus = SeasonStatus.Canceled;

                db.Entry(season).State = EntityState.Modified;

                db.SaveChanges();

                return RedirectToAction("Index", new { id = season.LeagueId });
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NOSWebApp/Controllers/LeaguesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NOSWebApp.Helpers;
using NOSWebApp.Models;

namespace NOSWebApp.Controllers
{
    [Authorize]
    public class LeaguesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Leagues
        [Authorize]
        public ActionResult Index(string errorMessage)
        {
            var leagues = db.Leagues.OrderBy(l => l.Name).ToList();

            if(leagues == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            ViewBag.ErrorMessage = errorMessage;
            return View(leagues);

        }                

        [Authorize(Roles = "LeagueAdmin")]
        // GET: Leagues/Create
        public ActionResult Create()
        {
            return View(new League());
        }

        // POST: Leagues/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "LeagueAdmin")]
        public ActionResult Create(League league)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Leagues.Add(league);
                    db.SaveChanges();

                    if (league.ImageUrl != null)
                    {
                        var folder = "~/Media/Leagues";
                        var file = $"{league.LeagueId}.png";

                        var response = FileHelper.UploadImage(league.ImageUrl, folder, file);

                        if (response)
                        {
                            var pic = $"{folder}/{file}";
                            league.LogoImage = pic;

                            db.Entry(league).State = EntityState.Modified;
                            db.SaveChanges();
                        }
                    }

                    return RedirectToAction("Index");
                }
                catch
                {
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
                }
            }

            return View(league);
        }

        // GET: Leagues/Edit/5
        [Authorize(Roles = "LeagueAdmin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            League league = db.Leagues.Find(id);
            

            if (league == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            return View(league);
        }

        // POST: Leagues/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "LeagueAdmin")]
        public ActionResult Edit([Bind(Include = "LeagueId,Name,Description,LogoImage,ImageUrl")]League league)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (league.ImageUrl != null)
                    {
                        var folder = "~/Media/Leagues";
                        var file = $"{league.LeagueId}.png";

                        var response = FileHelper.UploadImage(league.ImageUrl, folder, file);

                        if (response)
                        {
                            var pic = $"{folder}/{file}";
                            league.LogoImage = pic;
                        }
                    }

                    db.Entry(league).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch
                {
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
                }
            }

            return View(league);
        }

        // GET: Leagues/Delete/5
        [Authorize(Roles = "LeagueAdmin")]
        public ActionResult Disable(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            League league = db.Leagues.Find(id);
            if (league == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            if(league.Seasons.Where(s => s.SeasonStatus == SeasonStatus.WaitingToStart || s.SeasonStatus == SeasonStatus.InPogress).Count() != 0)
            {
                return RedirectToAction("Index", new { errorMessage = "You can't disable league that have pendant/ on going seasons!" });
            }

            if (!league.IsActive)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                league.IsActive = false;

                db.Entry(league).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        [Authorize(Roles = "LeagueAdmin")]
        public ActionResult Enable(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            League league = db.Leagues.Find(id);

            if(league == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            if (league.IsActive)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                league.IsActive = true;

                db.Entry(league);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NOSWebApp/Views/Leagues/Create.cshtml
@using Syncfusion.EJ2
@model NOSWebApp.Models.League

@{
    ViewBag.Title = "Create";
}

<h2>Create new League</h2>

@using (Html.BeginForm("Create", "Leagues", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-row", role = "form" }))
{
    @Html.AntiForgeryToken()

<div class="row w-100">

    <div class="col-12">
        @Html.ValidationSummary("", new { @class = "text-danger" })
    </div>

    <div class="col-6 ">

        <div class="row h-100 align-items-center">

            <div class="col-12">
                @Html.LabelFor(m => m.Name, new { @class = "" })
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control inputextShadow" })
            </div>



            <div class="col-12 mt-3">
                @Html.LabelFor(m => m.Description, new { @class = "" })
                @Html.TextBoxFor(m => m.Description, new { @class = "form-control inputextShadow" })
            </div>

        </div>


    </div>

    <div class="col-6">

        <div class="row text-center">

            <div class="col-12">
                League logo
            </div>

            <div class="col-12 mt-2">
                <img id="blah" src="~/Media/Shared/noImageAvailable.png" alt="Preview Image" height="200"/>
            </div>

            <div class="col-12 mt-2">
                @Html.TextBoxFor(model => model.ImageUrl, new { type = "file", id = "imgInp" })
            </div>

        </div>

    </div>

    <hr />

    <div class="col-12 mt-5">
        <input type="submit" value="Create" class="btn p3 btn-info" />
    </div>

    <div class="col-12 mt-2">
        <a href="@Url.Action("Index")">
            Back to leagues
        </a>
    </div>
</div>

    
}

<script>
    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#imgInp").change(function () {
        readURL(this);
    });
</script>

NOSWebApp/Views/Leagues/Edit.cshtml
@model NOSWebApp.Models.League

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Leagues", FormMethod.Post, new { enctype = "multipart/form-data", role = "form" }))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.LeagueId)
    @Html.HiddenFor(model => model.LogoImage)

    <div class="row w-100">

        <div class="col-12">
            @Html.ValidationSummary("", new { @class = "text-danger" })
        </div>

        <div class="col-6 ">

            <div class="row h-100 align-items-center">

                <div class="col-12">
                    @Html.LabelFor(m => m.Name, new { @class = "" })
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control inputextShadow" })
                </div>



                <div class="col-12 mt-3">
                    @Html.LabelFor(m => m.Description, new { @class = "" })
                    @Html.TextBoxFor(m => m.Description, new { @class = "form-control inputextShadow" })
                </div>

            </div>


        </div>

        <div class="col-6">

            <div class="row text-center">

                <div class="col-12">
                    League logo
                </div>

                <div class="col-12 mt-2">
                    <img id="blah" src="@Url.Content(Model.LogoImage)" alt="Preview Image" height="200" />
                </div>

                <div class="col-12 mt-2">
                    @Html.TextBoxFor(model => model.ImageUrl, new { type = "file", id = "imgInp" })
                </div>

            </div>

        </div>

        <hr />

        <div class="col-12 mt-5">
            <input type="submit" value="Save Changes" class="btn p3 btn-info" />
        </div>

        <div class="col-12 mt-2">
            <a href="@Url.Action("Index")">
                Back to leagues
            </a>
        </div>
    </div>


}

<script>
    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#imgInp").change(function () {
        readURL(this);
    });
</script>

NOSWebApp/Views/Leagues/Index.cshtml
@model IEnumerable<NOSWebApp.Models.League>

@{
    ViewBag.Title = "Leagues";
}

<h2>Leagues</h2>

@if (User.IsInRole("LeagueAdmin"))
{
    @Html.ActionLink("Create new League", "Create")

    <p class="text-danger">
        @ViewBag.ErrorMessage
    </p>
}

<div class="row">

    <div class="col-12">
        <a class="btn btn-primary w-100 mb-2" data-toggle="collapse" href="#al" role="button" aria-expanded="false" aria-controls="al">Active Leagues</a>
        <div class="collapse show" id="al">

            <div class="row">

                @foreach (var league in Model.Where(l => l.IsActive))
                {
                    <div class="col-xl-2 col-md-3 col-sm-4 col-6 align-baseline py-3">

                        <a href="@Url.Action("Index","League",new {id = league.LeagueId })" class="row h-100 align-items-center border py-3 mx-1" id="LeagueBox">

                            <div class="col-12 text-center pb-2">

                                @if (league.LogoImage != null)
                                {
                                    <img src="@Url.Content(league.LogoImage)" class="w-75 border border-dark" />
                                }
                            </div>

                            <div class="col-12 align-self-end text-center">
                                <span>@league.Name</span>
                            </div>

                        </a>

                        @if (User.IsInRole("LeagueAdmin"))
                        {
                            <div class="col-12 text-center p-0">
                                @Html.ActionLink("Edit", "Edit", new { id = league.LeagueId })
                                <span>  |  </span>
                                @Html.ActionLink("Disable", "Disable", new { id = league.LeagueId })
                            </div>
                        }

                    </div>
                }

            </div>

        </div>
    </div>



    <div class="col-12 mt-5">
        <a class="btn btn-primary w-100 mb-2" data-toggle="collapse" href="#dl" role="button" aria-expanded="false" aria-controls="dl">Inactive Leagues</a>
        <div class="collapse" id="dl">

            <div class="row">

                @foreach (var league in Model.Where(l => !l.IsActive))
                {
                    <div class="col-xl-2 col-md-3 col-sm-4 col-6 align-baseline py-3">

                        <a href="@Url.Action("Index","League",new {id = league.LeagueId })" class="row h-100 align-items-center border py-3 mx-1" id="LeagueBox">

                            <div class="col-12 text-center pb-2">

                                @if (league.LogoImage != null)
                                {
                                    <img src="@Url.Content(league.LogoImage)" class="w-75 border border-dark" />
                                }
                            </div>

                            <div class="col-12 align-self-end text-center">
                                <span>@league.Name</span>
                            </div>

                        </a>

                        @if (User.IsInRole("LeagueAdmin"))
                        {
                            <div class="col-12 text-center p-0">
                                @Html.ActionLink("Edit", "Edit", new { id = league.LeagueId })
                                <span>  |  </span>
                                @Html.ActionLink("Enable", "Enable", new { id = league.LeagueId })
                            </div>
                        }

                    </div>
                }

            </div>

        </div>
    </div>
</div>