NOSWebApp/Models/Club.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace NOSWebApp.Models
{
    public class Club
    {
        [Key]
        public int ClubId { get; set; }

        [Required]
        [MinLength(3)]
        public string Name { get; set; }

        public string Stadium { get; set; }

        public string Description { get; set; }

        public string LogoImage { get; set; } = "~/Media/Shared/noImageAvailable.png";

        public bool IsActive { get; set; } = true;

        public int? LeagueId { get; set; }
        public virtual League League { get; set; }

        [NotMapped]
        public virtual HttpPostedFileBase ImageUrl { get; set; }


        public virtual ICollection<Season> SeasonPlayed { get; set; }

        public virtual ICollection<GameMatch> GameMatches { get; set; }

        public virtual ICollection<ApplicationUser> Fans { get; set; }

        public virtual ICollection<SeasonBets> UserSeasonsBetted { get; set; }
    }
}

NOSWebApp/Controllers/ClubController.cs
using NOSWebApp.Helpers;
using NOSWebApp.Models;
using NOSWebApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace NOSWebApp.Controllers
{
    [Authorize]
    [HandleError]
    public class ClubController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Club
        [Authorize]
        public ActionResult Index(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "No Club Given");
            }

            Club club = null;
            try
            {
                 club = db.Clubs.FirstOrDefault(c => c.ClubId == id);

            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, ex.Message);
            }

            if(club == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound, "Club not Found");
            }

            ClubStatsView clubStatsView = new ClubStatsView
            {
                Club = club,
                SeasonsPlayed = club.SeasonPlayed.ToList(),
            };

            return View(clubStatsView);
        }

        [Authorize]
        public ActionResult AllStats(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "No Club Given");
            }

            Club club = null;
            try
            {
                club = db.Clubs.FirstOrDefault(c => c.ClubId == id);
            }
            catch(Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, ex.Message);
            }

            if (club == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound, "Club not Found");
            }

            List<GameMatch> clubGameMatches = null;

            try
            {
                clubGameMatches = db.GameMatches.Where(gm => gm.HomeClub.ClubId == club.ClubId || gm.AwayClub.ClubId == club.ClubId).ToList();
            }
            catch(Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, ex.Message);
            }

            if(clubGameMatches == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            ClubStatsView clubStatsView = null;

            try
            {
                clubStatsView = StatusHelper.MakeClubStats(club, clubGameMatches);
            }
            catch(Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, ex.Message);
            }

            if(clubStatsView == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            return View(clubStatsView);
        }

        [Authorize]
        public ActionResult AllSeasonClubStats(int? id, int? seasonId)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "No Club Given");
            }

            Club club = null;
            try
            {
                club = db.Clubs.FirstOrDefault(c => c.ClubId == id);
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, ex.Message);
            }

            if (club == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound, "Club not Found");
            }

            if (seasonId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "No Season Given");
            }

            List<GameMatch> clubGameMatches = null;

            try
            {
                clubGameMatches = db.GameMatches.Where(gm => (gm.HomeClub.ClubId == club.ClubId || gm.AwayClub.ClubId == club.ClubId) && gm.Fixture.SeasonId == seasonId).ToList();
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            if(clubGameMatches == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            ClubStatsView clubStatsView = null;

            try
            {
                clubStatsView = StatusHelper.MakeClubSeasonStats(club, clubGameMatches);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            if(clubStatsView == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            return View(clubStatsView);
        }

        [Authorize]
        public ActionResult ClubFans(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Club club = null;
            try
            {
             club =   db.Clubs.FirstOrDefault(c => c.ClubId == id);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            if(club == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            return View(club);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NOSWebApp/Controllers/ClubsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NOSWebApp.Helpers;
using NOSWebApp.Models;

namespace NOSWebApp.Controllers
{
    [Authorize]
    [HandleError]
    public class ClubsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Clubs
        [Authorize]
        public ActionResult Index(string errorMessage)
        {
            List<Club> clubs = null;

            try { clubs = db.Clubs.Include(c => c.League).ToList(); }
            catch { return new HttpStatusCodeResult(HttpStatusCode.InternalServerError); }

            if (clubs == null) { return new HttpStatusCodeResult(HttpStatusCode.InternalServerError); }

            ViewBag.ErrorMessage = errorMessage;
            return View(clubs.ToList());
        }


        // GET: Clubs/Create
        [Authorize(Roles = "LeagueAdmin")]
        public ActionResult Create()
        {
            List<League> leagues = null;

            try { leagues = db.Leagues.ToList(); }
            catch { return new HttpStatusCodeResult(HttpStatusCode.InternalServerError); }

            if(leagues ==null) { return new HttpStatusCodeResult(HttpStatusCode.InternalServerError); }

            leagues.Add(new League { Name = "[None]", LeagueId = 0 });
            ViewBag.LeagueId = new SelectList(leagues.OrderBy(l => l.Name), "LeagueId", "Name");


            return View();
        }

        // POST: Clubs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "LeagueAdmin")]
        public ActionResult Create([Bind(Include = "ClubId,Name,Stadium,Description,LogoImage,ImageURL,IsActive,LeagueId")] Club club)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (club.LeagueId == 0)
                    {
                        club.LeagueId = null;
                    }
                    db.Clubs.Add(club);
                    db.SaveChanges();

                    if (club.ImageUrl != null)
                    {
                        var folder = "~/Media/Clubs";
                        var file = $"{club.ClubId}.png";

                        var response = FileHelper.UploadImage(club.ImageUrl, folder, file);

                        if (response)
                        {
                            var pic = $"{folder}/{file}";
                            club.LogoImage = pic;

                            db.Entry(club).State = EntityState.Modified;
                            db.SaveChanges();
                        }
                    }

                    return RedirectToAction("Index");
                }
            }

            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            List<League> leagues = null;

            try { leagues = db.Leagues.ToList(); }
            catch { return new HttpStatusCodeResult(HttpStatusCode.InternalServerError); }

            if (leagues == null) { return new HttpStatusCodeResult(HttpStatusCode.InternalServerError); }

            leagues.Add(new League { Name = "[None]", LeagueId = 0 });
            ViewBag.LeagueId = new SelectList(leagues.OrderBy(l => l.Name), "LeagueId", "Name");

            return View(club);
        }

        // GET: Clubs/Edit/5
        [Authorize(Roles = "LeagueAdmin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Club club = db.Clubs.Find(id);

            if (club == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            List<League> leagues = null;

            try { leagues = db.Leagues.ToList(); }
            catch { return new HttpStatusCodeResult(HttpStatusCode.InternalServerError); }

            if (leagues == null) { return new HttpStatusCodeResult(HttpStatusCode.InternalServerError); }

            leagues.Add(new League { Name = "[None]", LeagueId = 0 });
            
            ViewBag.LeagueId = new SelectList(leagues.OrderBy(l => l.Name), "LeagueId", "Name",club.LeagueId);

            return View(club);
        }

        // POST: Clubs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "LeagueAdmin")]
        public ActionResult Edit([Bind(Include = "ClubId,Name,Stadium,Description,LogoImage,ImageURL,IsActive,LeagueId")] Club club)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (club.LeagueId == 0)
                    {
                        club.LeagueId = null;
                    }

                    if (club.ImageUrl != null)
                    {
                        var folder = "~/Media/Clubs";
                        var file = $"{club.ClubId}.png";

                        var response = FileHelper.UploadImage(club.ImageUrl, folder, file);

                        if (response)
                        {
                            var pic = $"{folder}/{file}";
                            club.LogoImage = pic;
                        }
                    }

                    db.Entry(club).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            List<League> leagues = null;

            try { leagues = db.Leagues.ToList(); }
            catch { return new HttpStatusCodeResult(HttpStatusCode.InternalServerError); }

            if (leagues == null) { return new HttpStatusCodeResult(HttpStatusCode.InternalServerError); }

            leagues.Add(new League { Name = "[None]", LeagueId = 0 });
            ViewBag.LeagueId = new SelectList(leagues.OrderBy(l => l.Name), "LeagueId", "Name", club.LeagueId);

            return View(club);
        }

        // GET: Leagues/Delete/5
        [Authorize(Roles = "LeagueAdmin")]
        public ActionResult Disable(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Club club = db.Clubs.Find(id);

            if (club == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            if (club.SeasonPlayed.Where(s => s.SeasonStatus == SeasonStatus.InPogress || s.SeasonStatus == SeasonStatus.WaitingToStart).Count() != 0)
            {

                return RedirectToAction("Index",new { errorMessage = "You can't disable clubs that are playing!" });
            }

            club.IsActive = false;

            db.Entry(club).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "LeagueAdmin")]
        public ActionResult Enable(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Club club = db.Clubs.Find(id);
            if (club == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            club.IsActive = true;

            

            try
            {
                db.Entry(club);
                db.SaveChanges();
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NOSWebApp/Views/Clubs/Create.cshtml
@model NOSWebApp.Models.Club

@{
    ViewBag.Title = "Create";
}

<h2>New Club</h2>

@using (Html.BeginForm("Create", "Clubs", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-row", role = "form" }))
{
    @Html.AntiForgeryToken()

<div class="row w-100">

    <div class="col-12">
        @Html.ValidationSummary("", new { @class = "text-danger" })
    </div>

    <div class="col-6 ">

        <div class="row h-100 align-items-center">

            <div class="col-12">
                @Html.LabelFor(m => m.Name, new { @class = "" })
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control inputextShadow" })
            </div>



            <div class="col-12 mt-3">
                @Html.LabelFor(m => m.Description, new { @class = "" })
                @Html.TextBoxFor(m => m.Description, new { @class = "form-control inputextShadow" })
            </div>

            <div class="col-12 mt-3">
                @Html.LabelFor(m => m.Stadium, new { @class = "" })
                @Html.TextBoxFor(m => m.Stadium, new { @class = "form-control inputextShadow" })
            </div>

        </div>


    </div>

    <div class="col-6">

        <div class="row text-center">

            <div class="col-12">
                Club logo
            </div>

            <div class="col-12 mt-2">
                <img id="blah" src="~/Media/Shared/noImageAvailable.png" alt="Preview Image" height="200" />
            </div>

            <div class="col-12 mt-2">
                @Html.TextBoxFor(model => model.ImageUrl, new { type = "file", id = "imgInp" })
            </div>

        </div>

    </div>

    <div class="col-12 mt-5">

        @Html.LabelFor(model => model.LeagueId, "League", htmlAttributes: new { @class = "" })
        @Html.DropDownList("LeagueId", null, htmlAttributes: new { @class = "form-control" })

        </div>

        <hr />

        <div class="col-12 mt-5">
            <input type="submit" value="Create" class="btn p3 btn-info" />
        </div>

        <div class="col-12 mt-2">
            <a href="@Url.Action("Index")">
                Back to clubs
            </a>
        </div>
    </div>


}

<script>
    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#imgInp").change(function () {
        readURL(this);
    });
</script>

NOSWebApp/Views/Clubs/Edit.cshtml
@model NOSWebApp.Models.Club

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Clubs", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-row", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ClubId)
    @Html.HiddenFor(model => model.LogoImage)
    <div class="row w-100">

        <div class="col-12">
            @Html.ValidationSummary("", new { @class = "text-danger" })
        </div>

        <div class="col-6 ">

            <div class="row h-100 align-items-center">

                <div class="col-12">
                    @Html.LabelFor(m => m.Name, new { @class = "" })
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control inputextShadow" })
                </div>



                <div class="col-12 mt-3">
                    @Html.LabelFor(m => m.Description, new { @class = "" })
                    @Html.TextBoxFor(m => m.Description, new { @class = "form-control inputextShadow" })
                </div>

                <div class="col-12 mt-3">
                    @Html.LabelFor(m => m.Stadium, new { @class = "" })
                    @Html.TextBoxFor(m => m.Stadium, new { @class = "form-control inputextShadow" })
                </div>

            </div>


        </div>

        <div class="col-6">

            <div class="row text-center">

                <div class="col-12">
                    Club logo
                </div>

                <div class="col-12 mt-2">
                    <img id="blah" src="@Url.Content(Model.LogoImage)" alt="Preview Image" height="200" />
                </div>

                <div class="col-12 mt-2">
                    @Html.TextBoxFor(model => model.ImageUrl, new { type = "file", id = "imgInp" })
                </div>

            </div>

        </div>

        <div class="col-12 mt-5">

            @Html.LabelFor(model => model.LeagueId, "League", htmlAttributes: new { @class = "" })
            @Html.DropDownList("LeagueId", null, htmlAttributes: new { @class = "form-control" })

        </div>

        <hr />

        <div class="col-12 mt-5">
            <input type="submit" value="Save Changes" class="btn p3 btn-info" />
        </div>

        <div class="col-12 mt-2">
            <a href="@Url.Action("Index")">
                Back to clubs
            </a>
        </div>
    </div>


}

<script>
    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#imgInp").change(function () {
        readURL(this);
    });
</script>

NOSWebApp/Views/Clubs/Index.cshtml
@model IEnumerable<NOSWebApp.Models.Club>

@{
    ViewBag.Title = "Clubs";
}

<h2>Clubs</h2>

@if (User.IsInRole("LeagueAdmin"))
{

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>

    <p class="text-danger">
        @ViewBag.ErrorMessage
    </p>
}



<div class="row">

    <div class="col-12">

        <div class="row justify-content-center">

            <div class="col-sm-6  text-center">

                <input type="text" id="leagueInput" onkeyup="SEARCHME()" placeholder="Search for leagues" class="">

            </div>

            <div class="col-sm-6 text-center">

                <input type="text" id="clubInput" onkeyup="SEARCHME()" placeholder="Search for clubs">

            </div>

        </div>

    </div>

    <div class="col-12">

        <div class="row justify-content-center">

            <div class="col-12 text-center mt-2">
                <a class="btn btn-primary w-100 mb-2" data-toggle="collapse" href="#cwlca" role="button" aria-expanded="false" aria-controls="cwlca">Active Clubs</a>
                <div class="collapse show row justify-content-center" id="cwlca">

                    <div class="table-responsive w-75">

                        <table id="clubsATable" class="table" style="border:1px solid white">

                            <thead>
                                <tr class="text-center">
                                    <th>League Name</th>
                                    <th>Club Name</th>
                                    <th>Club Description</th>
                                    <th>Club Stadium</th>
                                    <th>Club Fans</th>
                                    <th></th>
                                    @if (User.IsInRole("LeagueAdmin"))
                                    {
                                        <th></th>
                                        <th></th>
                                    }
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var club in Model.Where(c => c.IsActive).OrderBy(c => c.Name))
                                {
                                    <tr class="text-center">
                                        <td>@(club.League != null ? club.League.Name : "N/A")</td>
                                        <td>
                                            @if (club.LogoImage != null)
                                            {<img src="@Url.Content(club.LogoImage)" height="50" />}
                                            else
                                            {
                                                <img src="~/Media/Shared/noImageAvailable.png" height="50" />
                                            }
                                            @club.Name
                                        </td>
                                        <td>@club.Description</td>
                                        <td>@club.Stadium</td>
                                        <td>@club.Fans.Count()</td>
                                        <td>@Html.ActionLink("View", "Index", "Club", new { id = club.ClubId }, null)</td>
                                        @if (User.IsInRole("LeagueAdmin"))
                                        {
                                            <td>@Html.ActionLink("Edit", "Edit", new { id = club.ClubId })</td>
                                            <td>@Html.ActionLink("Disable", "Disable", "Clubs", new { id = club.ClubId }, null)</td>
                                        }
                                    </tr>
                                }
                            </tbody>

                        </table>

                    </div>

                </div>
            </div>

            <div class="col-12" style="border:solid 20px transparent">

            </div>

            <div class="col-12 text-center mt-2">
                <a class="btn btn-primary w-100 mb-2" data-toggle="collapse" href="#cwlcd" role="button" aria-expanded="false" aria-controls="cwlcd">Inactive Clubs</a>

                    <div class="collapse show row justify-content-center" id="cwlcd">

                        <div class="table-responsive w-75">

                            <table id="clubsITable" class="table" style="border:1px solid white">

                                <thead>
                                    <tr class="text-center">
                                        <th>League Name</th>
                                        <th>Club Name</th>
                                        <th>Club Description</th>
                                        <th>Club Stadium</th>
                                        <th>Club Fans</th>
                                        <th></th>
                                        @if (User.IsInRole("LeagueAdmin"))
                                        {
                                            <th></th>
                                            <th></th>
                                        }
                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach (var club in Model.Where(c => !c.IsActive).OrderBy(c => c.Name))
                                    {
                                        <tr class="text-center">
                                            <td>@(club.League != null ? club.League.Name : "N/A")</td>
                                            <td>
                                                @if (club.LogoImage != null)
                                                {<img src="@Url.Content(club.LogoImage)" height="50" />}
                                                else
                                                {
                                                    <img src="~/Media/Shared/noImageAvailable.png" height="50" />
                                                }
                                                @club.Name
                                            </td>
                                            <td>@club.Description</td>
                                            <td>@club.Stadium</td>
                                            <td>@club.Fans.Count()</td>
                                            <td>@Html.ActionLink("View", "Index", "Club", new { id = club.ClubId }, null)</td>
                                            @if (User.IsInRole("LeagueAdmin"))
                                            {
                                                <td>@Html.ActionLink("Edit", "Edit", new { id = club.ClubId })</td>
                                                <td>@Html.ActionLink("Enable", "Enable", "Clubs", new { id = club.ClubId }, null)</td>
                                            }
                                        </tr>
                                    }
                                </tbody>

                            </table>

                        </div>

                    </div>

            </div>


        </div>

    </div>

</div>

<script>

    function SEARCHME() {

        var leagueInput, leagueFilter;
        var clubInput, clubFilter;
        var table, tr, tdLeague,tdClub, i, txtValueLeague, txtValueClub;

        leagueInput = document.getElementById("leagueInput");
        leagueFilter = leagueInput.value.toUpperCase();

        clubInput = document.getElementById("clubInput");
        clubFilter = clubInput.value.toUpperCase();

        table = document.getElementById("clubsATable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            tdLeague = tr[i].getElementsByTagName("td")[0];
            tdClub = tr[i].getElementsByTagName("td")[1];

            if (tdLeague || tdClub) {
                txtValueLeague = tdLeague.textContent || tdLeague.innerText;
                txtValueClub = tdClub.innerText;

                

                if (txtValueLeague.toUpperCase().indexOf(leagueFilter) > -1 && txtValueClub.toUpperCase().indexOf(clubFilter) > -1) {
                    tr[i].style.display = "";
                }
                else {
                    tr[i].style.display = "none";
                }
            }
        }

        table = document.getElementById("clubsITable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            tdLeague = tr[i].getElementsByTagName("td")[0];
            tdClub = tr[i].getElementsByTagName("td")[1];

            if (tdLeague || tdClub) {
                txtValueLeague = tdLeague.textContent || tdLeague.innerText;
                txtValueClub = tdClub.innerText;

                

                if (txtValueLeague.toUpperCase().indexOf(leagueFilter) > -1 && txtValueClub.toUpperCase().indexOf(clubFilter) > -1) {
                    tr[i].style.display = "";
                }
                else {
                    tr[i].style.display = "none";
                }
            }
        }
    }

</script>